pushed

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,12 +1,19 @@
-#!/usr/bin/env bash
-# uploads a file to a server
+#!/bin/bash
 
-msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-
-if [ "$4" ]; then
-   scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
-elif [ "$3" ]; then
-     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
-else
-	echo "$msg";
+# Check if the number of arguments is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
+
+# Assign arguments to variables
+FILE_PATH="$1"
+IP_ADDRESS="$2"
+USERNAME="$3"
+SSH_KEY_PATH="$4"
+
+# Transfer file using scp
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME"@"$IP_ADDRESS":~/ || { echo "Error transferring file."; exit 1; }
+
+echo "$FILE_PATH transferred successfully to $USERNAME@$IP_ADDRESS:~/"
+
